export { default as Library } from './Library';
export { default as Home } from './Home';
export { default as Tavern } from './Tavern';
export { default as Painting } from './Painting';
export { default as Sculpture } from './Sculpture';
export { default as Bookcase } from './Bookcase';
export { default as Fireplace } from './Fireplace';
export { default as Сabinet } from './Сabinet';
export { default as Safe } from './Safe';